### ISSUE TITLE
Table Of Contents View Feature Request

### ISSUE THREAD

**Issue by pmurphyjam** [vfr/Reader#103]
Any way you could add a Table Of Contents View so users could use this to get to a specific page in the PDF quickly. Dropbox has this feature and it's quite nice.
  Very nice code by the way, and works great!

**Comment by jvanakker** [comment]
+1, a table of contents view would really enhance this project. Are there any plans for this?

**Comment by jerald-acacus** [comment]
+1

**Comment by Fexxel** [comment]
+1
