### ISSUE TITLE
I found problem when after zoom.

### ISSUE THREAD

**Issue by anutakoon** [vfr/Reader#106]
Hi. owner. 
I thank you for this library.
Cloud I found the problem about zoom page.
This step
1. Slide to next 2 pages
2. Zoom maximum and scroll to next page or previous page. 
3. That page frozen. but it can zoom. 

I use v2.8.6
I need somebody to help me. TT_TT
I  solved this problem for three days.
I hope somebody to help me. Thanks.

**Comment by mikelrmb** [comment]
hi bro you sol yet? i met the same problem

**Comment by DemonToby** [comment]
the same ..........

**Comment by yuzhiyou2009** [comment]
i met the same problem,is there any solution?

**Comment by LiuChang712** [comment]
the same，how to solve???
