### ISSUE TITLE
iOS 8.3 E-Mail From

### ISSUE THREAD

**Issue by marco783** [vfr/Reader#113]
I have a problem with the MFMailComposeViewController.
When a user (with iOS 8.3) tries to change the sender, he remains locked in the selection screen and he can't go back in any way.
The selection screen of the sender opens full screen and not as a popover like with iOS 8.2.

**Comment by jamesince** [comment]
Comment out this line in ReaderViewController.m, it will work fine.
// mailComposer.modalPresentationStyle = UIModalPresentationFormSheet;
I did not test back on iOS 8.2, may you need to check the version and do an if.
