### ISSUE TITLE
Image resources loading problem 

### ISSUE THREAD

**Issue by diegothucao** [vfr/Reader#114]
Dear friends,
I am using Reader, it is really nice. I used 
pod 'Reader', :git => 'https://github.com/vfr/Reader.git'

However, when the app running, the buttons do not show icons. No icons at all.

If I manually add all icons to the projects, it runs well.

Could you let me know my problem or can you fix this bug for next version 

Thanks

Thu

**Comment by amosavian** [comment]
Hi,
I think it's better to use image assets if you add files manually.

**Comment by pnome** [comment]
I had the same issue installing with Cocoapods.  I'd love to know what's going wrong

**Comment by mustafaibrahim989** [comment]
+1

**Comment by mustafaibrahim989** [comment]
I created a pull request for this fix #145 use `pod 'vfrReader',:git => 'https://github.com/mustafaibrahim989/Reader.git'` till we can merge and release.
