### ISSUE TITLE
Search Text in pdf 

### ISSUE THREAD

**Issue by tucano3000** [vfr/Reader#116]
Is possible search text in pdf file with url scheme ?

**Comment by tucano3000** [comment]
i found this to the project
http://web.archive.org/web/20131122162015/http://blog.random-ideas.net/?p=184

**Comment by katopz** [comment]
I found this https://github.com/KurtCode/PDFKitten

**Comment by tucano3000** [comment]
I am newbee in Objective C and i don't know how to install and use this framework PDFKitten in PDF Reader Core. Anybody Can do some tutorial ?

**Comment by soulshined** [comment]
see the closed pull request here : https://github.com/vfr/Reader/pull/94
