### ISSUE TITLE
Is PDF cached?

### ISSUE THREAD

**Issue by mputnamtennessee** [vfr/Reader#122]
I create a PDF, save it to the Documents Directory, and use Reader to display. Fine.
I delete the PDF from the Documents Directory, AND CONFIRM THAT IT IS REALLY GONE.
I create another PDF with the same filename, but when I go to display it, Reader actually shows me the first PDF.

Ideas?

**Comment by vfr** [comment]
Delete the app from the simulator or device after changing the PDF. Xcode
might not be updating the file when it pushes out the build to simulator or
device. Another thing to watch out for is page thumbnail caching. If you
change the PDF, you need to purge the thumbnails from the cache for that
document.

  _____

**Comment by mputnamtennessee** [comment]
Thanks,
That did it.
MP

> On Aug 18, 2015, at 12:19 PM, Julius Oklamcak <notifications@github.com> wrote:
> 
> Delete the app from the simulator or device after changing the PDF. Xcode
> might not be updating the file when it pushes out the build to simulator or
> device. Another thing to watch out for is page thumbnail caching. If you
> change the PDF, you need to purge the thumbnails from the cache for that
> document.
> 
> _____ 
> 
> From: mputnamtennessee [mailto:notifications@github.com] 
> Sent: Tuesday, August 18, 2015 12:37 PM
> To: vfr/Reader
> Subject: [Reader] Is PDF cached? (#122)
> 
> 
> 
> I create a PDF, save it to the Documents Directory, and use Reader to
> display. Fine.
> I delete the PDF from the Documents Directory, AND CONFIRM THAT IT IS REALLY
> GONE.
> I create another PDF with the same filename, but when I go to display it,
> Reader actually shows me the first PDF.
> 
> Ideas?
> 
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/vfr/Reader/issues/122> .
> <https://github.com/notifications/beacon/AAX4vykSaqaaae3ftNVhhZ-F2Z8yiaNrks5
> oo1aZgaJpZM4Ftt8U.gif> 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/vfr/Reader/issues/122#issuecomment-132285234>.
> 

:: :: :: :: :: :: :: :: :: :: :: :: :: ::

Mark Putnam
(615) 512-1038
mark@markandlori.com <mailto:mark@markandlori.com>
Get your copy of my new novel Caves of Qobustan <http://www.lulu.com/product/hardcover/caves-of-qobustan/13660801?productTrackingContext=author_spotlight_64834913_> at Lulu.
Check out my new iPhone app for Artists - ValueViewer <http://itunes.apple.com/app/valueviewer/id431548079?mt=8> - at the Apple Store on your iPhone.
Learn more about my cooking and trekking workshops around the world at markandlori.com <http://markandlori.com/workshops>.
:: :: :: :: :: :: :: :: :: :: :: :: :: ::
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient or have received this e-mail in error please notify the sender immediately and destroy this e-mail.
Questa e-mail può contenere informazioni confidenziali e/o riservate. Se ritiene di non essere il corretto destinatario della stessa o di aver ricevuto la stessa per errore notifichi immediatamente l'accaduto al mittente e distrugga il messaggio.

**Comment by qasimmehboob** [comment]
I am having issue with thumbnails. they are not updating when i load new pdf. how can i purge the thumbnails from the cache?.
