### ISSUE TITLE
error when pushViewController

### ISSUE THREAD

**Issue by thanawatSuj** [vfr/Reader#125]
ReaderViewController _readerViewController = [[ReaderViewController alloc] initWithReaderDocument:document];
        readerViewController.delegate = self;
        window = [[[UIApplication sharedApplication]delegate]window];
        navigaition = (UINavigationController_)window.rootViewController;
        [navigaition pushViewController:readerViewController animated:YES];

error When i press back on NavigationViewController.

No Message error in log.

Thank you.

**Comment by jbranc** [comment]
+1
