### ISSUE TITLE
Remote PDF from an NSURL?

### ISSUE THREAD

**Issue by NaderKhedhri** [vfr/Reader#128]
Hi, thanks for this great work i would like to ask how i can read pdf files from url with this projects I've used nsurl but without results ?

**Comment by rico237** [comment]
Download your PDF first, then convert it into NSData then display it using the Reader

**Comment by ankiinn** [comment]
@rico237 @NaderKhedhri  how to display NSData using the Reader? SR my english is not good

**Comment by rico237** [comment]
@NaderKhedhri you have to save your data in NSBundle or get the file path (NSString) of the pdf you downloded then use the code in function "handleSingleTap" here : https://github.com/vfr/Reader/blob/master/Classes/ReaderDemoController.m
