### ISSUE TITLE
iOS 9, deprecated rotation methods, ReaderViewController frame sizes

### ISSUE THREAD

**Issue by rex12** [vfr/Reader#132]
- I am using this library in my iPad split view project. PDF reader is shown in a popover. Since iOS 9, I notice that PDF document is not centered properly and the frame for scrollview and main page bar is not set correctly. After rotating the device everything gets fixed and shown fine.
- There are deprecated methods (since iOS 8) such as _willRotateToInterfaceOrientation, willAnimateRotationToInterfaceOrientation,  didRotateFromInterfaceOrientation_. 
  Are you planning to make relevant updates?

BTW, thanks for this wonderful library, you did really good job.

**Comment by jel111** [comment]
What about stack view?
