### ISSUE TITLE
iphone 5 and below swiping between pages sometimes stucked,

### ISSUE THREAD

**Issue by trd-paolo** [vfr/Reader#134]
When I compile the app and test on iphone 4s simulator, 
when you swipe between pages, there are times that it is unable to swipe. and just stuck on the same page no matter how many times you swipe again, unless you tap it once and swipe again...

**Comment by Dev1an** [comment]
I'm having this problem too. Not only in the simulator but also on my iPhone 5

**Comment by x2rider** [comment]
I'm not sure if this is related, but even on iOS9.3.3, I am noticing if you scroll too fast, the page never renders.  You end up having to scroll back to the last page viewed, then slowly go page by page.  If this is what you're seeing, I have a fix and am trying to do a pull request to submit my changes.
