### ISSUE TITLE
text selection

### ISSUE THREAD

**Issue by syrakozz** [vfr/Reader#137]
can you plz add text selection feature for english and arabic text

**Comment by GaneshKumarSelvam** [comment]
hey @syrakozz have you got any idea on how to select the text in this reader.

**Comment by jaybowong** [comment]
Really need this.

@syrakozz you opened this issue in 2015 and it is 2017. Have you found any solution or alternative? I'm concerned that the author might not interested in implementing this.

I'm thinking about switching to [FastPdfKit](https://github.com/mobfarm/FastPdfKit).
