### ISSUE TITLE
Second time crash when open PDF  

### ISSUE THREAD

**Issue by phaihandoi** [vfr/Reader#139]
I downloaded a Pdf file, move it to document after read PDF file from url of document , 
First time it is ok,
Close app, and open again CRASH 
**\* Assertion failure in -[ReaderContentPage initWithURL:page:password:], /Users/hungnh/Desktop/Book/Pods/vfrReader/Sources/ReaderContentPage.m:489
2015-12-25 10:48:54.913 Book[75703:4118246] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'CGPDFDocumentRef == NULL'
Please help me, 
Thank you very much .
[Book  12-25-15, 10-53 AM.crash.txt](https://github.com/vfr/Reader/files/72021/Book.12-25-15.10-53.AM.crash.txt)

**Comment by feimamura** [comment]
I have the same problem
