### ISSUE TITLE
not saving bookmarks and remembering the page number when dismiss readerViewController

### ISSUE THREAD

**Issue by superzheng88** [vfr/Reader#141]
When I dismiss the ReaderViewController and present it again, it can't save the bookmarks and remember the page I have read. I don't know what's going wrong, thank you!

**Comment by xxcombat** [comment]
I have the same problem.

**Comment by xxcombat** [comment]
I found a solution to the problem.
it is not right
-            if let document = PDFReaderDocument(filePath: filePath, password: nil) {..............

it is right
+            if let document = PDFReaderDocument.withDocumentFilePath(filePath, password:nil) as? PDFReaderDocument {..............
