### ISSUE TITLE
installing pod file error

### ISSUE THREAD

**Issue by ruffdrum** [vfr/Reader#144]
Hi,

I am getting a error

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `vfrReader (~> 2.8.7)` required by `Podfile`

when installing the podfile. Any ideas?

**Comment by ruffdrum** [comment]
Sorted the issue by just using

pod 'vfrReader'

ended up loading 2.8.6 instead

**Comment by saravananNV** [comment]
hi rufffdrum
  how can i integrate with this reader app to a swift application.
