### ISSUE TITLE
Right to left Order

### ISSUE THREAD

**Issue by kevinonik** [vfr/Reader#148]
It will be great help if you tell me how to make it begin from right. RTL issue

@vfr

**Comment by amrabdelaal** [comment]
you can make transform rotation by 180 for scrollview then another rotation transform for content view inside scrollview

**Comment by dawand** [comment]
@amrabdelaal can you clarify your answer? rotating the view will change it to upside down!

**Comment by senseimeshari** [comment]
@amrabdelaal Thank you so much. Really helpful.

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
