### ISSUE TITLE
how to integrate with ios app using swift

### ISSUE THREAD

**Issue by saran-metron** [vfr/Reader#155]
Hi,

can you please tell me how to integrate with this pdf reader ios application using swift language

**Comment by fallaha13** [comment]
Use Cocoapods

**Comment by EnesKaraosman** [comment]
after you added the files mentioned, also create a Bridging-Header;(http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift)

Then you can use ;(in storyboard, I have a button to show a View to display PDF, and make sure this view's Custom Class is set to ReaderViewController)

class ViewController: UIViewController, ReaderViewControllerDelegate {
//
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if document != nil {
            let readerViewController:ReaderViewController  = ReaderViewController(readerDocument: document)
            readerViewController.delegate = self ;
            readerViewController.modalTransitionStyle = .CrossDissolve;
            readerViewController.modalPresentationStyle = .FullScreen;
            self.navigationController?.navigationBarHidden = true
            self.presentViewController(readerViewController, animated: true, completion: nil)   
            readerViewController.navigationController?.navigationBarHidden = false
        }  
    }   
}
