### ISSUE TITLE
When frame of ReaderViewController changed by UISplitViewController content is not adjusted properly

### ISSUE THREAD

**Issue by leszarna** [vfr/Reader#156]
I spent time to experiment to fix this, and what's worse I can see you have code in pull request but it seems to be not integrated to main branch. Why ? Can we solve this ?
Here is link to pull request :
https://github.com/vfr/Reader/pull/15/commits/084ea9d29f48eda984741d2c5629928d45c8c543

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
