### ISSUE TITLE
Problem VFR Reader with integrating Swift Application

### ISSUE THREAD

**Issue by saravananNV** [vfr/Reader#157]
Hi,

I am working with integrating this vrf reader with swift application. i am working with pod installation. i have implemented with all logic in the controller. my pdf was inside the project. in my own view controller i have extended the ReaderViewControllerDelegate and the coding was here:

import vfrReader
import QuartzCore
import ImageIO
import MessageUI

class ViewController: UIViewController,ReaderViewControllerDelegate {

var document = ReaderDocument()
override func viewDidLoad() {
super.viewDidLoad()
let pdfLoc: String = NSBundle.mainBundle().pathForResource("sample", ofType: "pdf")!
document = ReaderDocument.withDocumentFilePath(pdfLoc, password: nil)
var readerViewController: ReaderViewController = ReaderViewController(readerDocument: document)
readerViewController.delegate = self
self.presentViewController(readerViewController, animated: true, completion: nil)

}

after build and running , i am getting plain view with warning

Warning:

PDFViewerSample[7224:150218] Warning: Attempt to present <ReaderViewController: 0x7a76f8c0> on <PDFViewerSample.ViewController: 0x7b9670a0> whose view is not in the window hierarchy!

**Comment by icome2kill** [comment]
As far as I am understanding, you are trying to have your readerViewController show up entirely on top of your current ViewController, right?

If that was the case. the code should be like this: 

override func viewDidLoad() {
    super.viewDidLoad()
    let pdfLoc: String = NSBundle.mainBundle().pathForResource("sample", ofType: "pdf")!
    document = ReaderDocument.withDocumentFilePath(pdfLoc, password: nil)

    readerViewController.view.frame = self.view.frame
    self.addChildViewController(readerViewController)
    self.view.addSubview(readerViewController.view)
    readerViewController.didMoveToParentViewController(self)
}
