### ISSUE TITLE
why is the 2.8.7 not released in the cocoapods podspec?

### ISSUE THREAD

**Issue by nvzsolutions** [vfr/Reader#158]
https://cocoapods.org/pods/vfrReader
it shows 2.8.6

https://github.com/CocoaPods/Specs/tree/master/Specs/vfrReader
Can you update the specs?

**Comment by LemonRuss** [comment]
You can easy install it like this 
 pod 'vfrReader', :git => 'https://github.com/vfr/Reader'

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
