### ISSUE TITLE
 iOS 10 beta 1: Crash on CGContextDrawPDFPage

### ISSUE THREAD

**Issue by NasH5169** [vfr/Reader#161]
Hi all,

I'm currently validating my app on iOS 10 beta 1.

Sometimes, while loading or changing the pages of a PDF, vfrReader crashs with EXC_BAD_ACCESS at this line:

**CGContextDrawPDFPage(context, _PDFPageRef);**

I'm currently debugging but I wanted to open an issue if anybody have some informations or fix to share.

Good luck all.

```
- (void)drawLayer:(CATiledLayer *)layer inContext:(CGContextRef)context
{
	ReaderContentPage *readerContentPage = self; // Retain self

	CGContextSetRGBFillColor(context, 1.0f, 1.0f, 1.0f, 1.0f); // White

	CGContextFillRect(context, CGContextGetClipBoundingBox(context)); // Fill

	//NSLog(@"%s %@", __FUNCTION__, NSStringFromCGRect(CGContextGetClipBoundingBox(context)));

	CGContextTranslateCTM(context, 0.0f, self.bounds.size.height); CGContextScaleCTM(context, 1.0f, -1.0f);

	CGContextConcatCTM(context, CGPDFPageGetDrawingTransform(_PDFPageRef, kCGPDFCropBox, self.bounds, 0, true));

	//CGContextSetRenderingIntent(context, kCGRenderingIntentDefault); CGContextSetInterpolationQuality(context, kCGInterpolationDefault);

	CGContextDrawPDFPage(context, _PDFPageRef); // Render the PDF page into the context

	if (readerContentPage != nil) readerContentPage = nil; // Release self
}
```

**Comment by NasH5169** [comment]
In iOS 10 beta 2, no problem... Seems to be revolve so it was a beta 1 bug :)

**Comment by RandyJackson37336** [comment]
in iOS 10 release。Memory leak，and app is crash。I don't know  how to solve this bug？

**Comment by hccgk** [comment]
Xcode Version 8.2.1 (8C1002)

ios Version 10.2 14C92 

also  Crash why ? code problem?  

do you do something with this code ?
