### ISSUE TITLE
Opening a file from local URL file path

### ISSUE THREAD

**Issue by fallaha13** [vfr/Reader#162]
Hello, I have been working with this issue for quite a while. I acquire a PDF document as an NSData type and I try to write it to my local file system. However the file path says its null but I did download the Data. Thoughts?

`
      '  let paths  = NSSearchPathForDirectoriesInDomains(.AllLibrariesDirectory,.UserDomainMask, true)
        print(paths)
        let documentsDirectory = paths[0]
        let finalPath = documentsDirectory.stringByAppendingString("/FitForTwo.pdf")'

    
        let downloadTask = storageRef.dataWithMaxSize(10 * 1024 * 1024) { (data: NSData?, error: NSError?) in
            if (error != nil) {
                print("ERRORORRPR")
                // Uh-oh, an error occurred!
            } else {
            
                if let localURL = NSURL(string: finalPath) {
                    print(NSBundle.allBundles())
                    data?.writeToURL(localURL, atomically: true)
                    print("Attempting to open")
                    print(finalPath)
        
                    let document: ReaderDocument =  ReaderDocument.withDocumentFilePath(finalPath, password: nil)
                    
                    let readerVC: ReaderViewController = ReaderViewController.init(readerDocument: document)
                    
                    readerVC.delegate = self
                    readerVC.modalTransitionStyle = UIModalTransitionStyle.CrossDissolve
                    readerVC.modalPresentationStyle = UIModalPresentationStyle.FullScreen
                    self.presentViewController(readerVC, animated: true, completion: nil)

                }
            }
        }
`

**Comment by shingsoso** [comment]
Have you solved it ?

**Comment by fallaha13** [comment]
Hi,

Yeah. This is kind of late though. Works great.

-Alex

________________________________

**Comment by shingsoso** [comment]
Could you give me some hints on this problem, as I got the same trouble recently. Thank you!

**Comment by fallaha13** [comment]
`let popPDFS = NSBundle.mainBundle().pathsForResourcesOfType("pdf", inDirectory: nil)
        let popFilePath = popPDFS.first
        let popDoc = ReaderDocument.init(filePath: popFilePath, password: nil)
        //Init a reader document object
        
        let storage = FIRStorage.storage()
        print(storage) // print the
        let storageRef = storage.referenceForURL((plan?.downloadURL)!)
        
        let paths  = NSSearchPathForDirectoriesInDomains(.DocumentDirectory,.UserDomainMask, true)
        print(paths)
        let documentsDirectory = paths[0]
        let finalPath = documentsDirectory.stringByAppendingString("/\((plan?.pdf)!).pdf")
        
        let path = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)[0] as String
        let url = NSURL(fileURLWithPath: path)
        let filePath = url.URLByAppendingPathComponent("/\((plan?.pdf)!).pdf")!.path!
        let fileManager = NSFileManager.defaultManager()
        if fileManager.fileExistsAtPath(filePath) {
            print("FILE AVAILABLE")
            if let localURL = NSURL(string: filePath) {
                print("Attempting to open")
                
                if let doc1 = ReaderDocument.withDocumentFilePath(filePath, password: nil) as? ReaderDocument {
                    print("okay doc1  \(doc1) ")
                    let readerVC: ReaderViewController = ReaderViewController.init(readerDocument: doc1)
                    
                    readerVC.delegate = self
                    readerVC.modalTransitionStyle = UIModalTransitionStyle.CrossDissolve
                    readerVC.modalPresentationStyle = UIModalPresentationStyle.FullScreen
                    self.presentViewController(readerVC, animated: true, completion: nil)
                    
                }
                
                
            }
            
        } else {
            print("FILE NOT AVAILABLE")
            let downloadTask = storageRef.dataWithMaxSize(10 * 1024 * 1024) { (data: NSData?, error: NSError?) in
                if (error != nil) {
                    self.showErrorAlert("Error", msg: "Could not download, please try again.")
                    print("ERRORORRPR")
                } else {
                    if let localURL = NSURL(string: finalPath) {
                        print("Attempting to open")
                        data?.writeToFile(finalPath, atomically: true)
                        if let doc1 = ReaderDocument(filePath: finalPath, password: nil)  as? ReaderDocument {
                            print("okay doc1  \(doc1) ")
                            let readerVC: ReaderViewController = ReaderViewController.init(readerDocument: doc1)
                            
                            
                            
                            readerVC.delegate = self
                            readerVC.modalTransitionStyle = UIModalTransitionStyle.CrossDissolve
                            readerVC.modalPresentationStyle = UIModalPresentationStyle.FullScreen
                            self.presentViewController(readerVC, animated: true, completion: nil)
                        }
                    }
                }
            }
         
        }
        
`
Please keep in mind this is Swift 2.3.

In this example, I downloaded a PDF file from Firebase, referenced from the plan object and displayed it. I hope this helps. Let me know if you have anymore questions.

**Comment by shingsoso** [comment]
It works like a charm after i did some adjustment ! Thank you so much :)

**Comment by fallaha13** [comment]
glad I could help 👍
