### ISSUE TITLE
Can i read directly PDF File from NSData

### ISSUE THREAD

**Issue by stevienguyen1988** [vfr/Reader#169]
Hi 

I have a question. I save my pdf file in database in Data format. Because of that i dont have file path to pdf file. I want to know if there are anyway to create ReaderDocument Object without filePath.

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
