### ISSUE TITLE
On IOS 10.1 device,any pdfs can't be display

### ISSUE THREAD

**Issue by luotao001** [vfr/Reader#172]
On IOS 10.1 device,many pdfs can't be displayed,but on ios 9 and ios 8,these pdfs can be displayed.
I can't fix this bug.

please download my pdf and test this issues:
http://www.ioscndeveloper.cn/audio/test.pdf

**Comment by ramrcram** [comment]
Hello, 
Any Update on this issue? i am also facing the same issue.

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
