### ISSUE TITLE
weak Reference not support.

### ISSUE THREAD

**Issue by jeffluon** [vfr/Reader#173]
Cocoapod version 1.1.1

pod 'vfrReader',        :podspec =>  'library/podspecs/Reader.podspec', :inhibit_warnings => true

Build by Xcode 8.0

@synthesize message;
/VST/local/docBeat-iOS/Pods/vfrReader/Sources/ReaderContentView.m:64:13: Cannot synthesize weak property because the current deployment target does not support weak references

**Comment by jeffluon** [comment]
Thanks,
After I updated version 1.2.0.beta, I got the real reason.

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
