### ISSUE TITLE
Change Constant Macros when installing via cocapods

### ISSUE THREAD

**Issue by joaomvfsantos** [vfr/Reader#174]
How can one change a macro, let's say READER_BOOKMARKS when using the library via Cocoapods?

**Comment by aborigeno** [comment]
I was wondering the same thing

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
