### ISSUE TITLE
Crash app because leak memory when open scaned pdf

### ISSUE THREAD

**Issue by mua53** [vfr/Reader#175]
I have problem with some file pdf scan. When i open it, memory dont release when i read new page. But some pdf scan not have problem same, pdf covert from doc, pp ... are oke. Here is one of files pdf have problem: [https://www.dropbox.com/s/x492x3cpynpm4yl/A8dbY4UaM53xi.pdf?dl=0](pdf). Digital resolution isn't reason.
p/s: So sorry, my english is bad

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
