### ISSUE TITLE
how to Get Password Protected PDF hyperlinks(URL) on iOS 10.2

### ISSUE THREAD

**Issue by ravindhiran** [vfr/Reader#177]
I've spent all day trying to get hyperlinks metadata from **password protected PDFs** in my iPad application.

I tried **without password Protected PDF** in my ipad application it **works proper** everything.also password protected PDF hyperlinks works proper below ios 10.2 version.

only the problem is ios 10.2 & above version

Step 1: (Download pdf reader app from below link)

https://github.com/vfr/Reader

Step 2 : (Download my custom pdf from below link)

http://docdro.id/eAtlQ8z

password : 205062PY1el8@JfoZm90gdUCMKTD!NhH5xabrvEzu7kFWq6iRO

while tap on Hyperlink getting below error:

-[ReaderContentPage annotationLinkTarget:] Bad URI '(null)'

http://stackoverflow.com/questions/42022107/get-password-protected-pdf-hyperlinksurl-on-ios-10-2

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
