### ISSUE TITLE
Publish to CocoaPods

### ISSUE THREAD

**Issue by Vortec4800** [vfr/Reader#58]
Would it be possible to tag the releases in GitHub and publish the library to CocoaPods? I see you already have a pod file, so most of the work should be done already. Instructions to publish are available here:

http://guides.cocoapods.org/making/getting-setup-with-trunk

Thanks!

**Comment by azeitler** [comment]
as there's no progress on this, can I ask you to tag the commits in this repo with the according version numbers?

this way we can just do a ```pod 'Reader', :podspec => 'https://raw.githubusercontent.com/vfr/Reader/master/Reader.podspec'``` to include the repo as a pod.

currently I get a 

    Installing Reader (2.8.5)
    [!] Pod::Executable fetch origin tags/v2.8.5 2>&1
    fatal: Couldn't find remote ref tags/v2.8.5
    fatal: The remote end hung up unexpectedly

when trying to do that.

**Comment by buley** [comment]
This would be very useful to me :+1:

**Comment by Reedyuk** [comment]
Yes, another from me too, please can you sort this out so its on cocoapods.

Thanks

**Comment by jsetting32** [comment]
Would definitely be awesome!

**Comment by malarkannaninvention** [comment]
It is may 2015 already. :disappointed:

**Comment by inzinga** [comment]
Please help with finalizing cocoapods integration!!! 🙏

**Comment by brandonking** [comment]
Julius, I'm willing to update the vfrReader spec for CocoaPods.  Let me know if you're interested.

**Comment by WingedToaster** [comment]
:+1: :pray:

**Comment by vfr** [comment]
Done... Finally!

**Comment by WingedToaster** [comment]
Woohoo!

**Comment by brandonking** [comment]
Thanks @vfr!  I'll go change my podfile and try it out.

**Comment by sibeliusseraphini** [comment]
@brandonking how can I add this lib using cocoapods

**Comment by WingedToaster** [comment]
pod 'vfrReader' 

should work

**Comment by sibeliusseraphini** [comment]
thanks
