### ISSUE TITLE
2 page spreads on iPad Landscape

### ISSUE THREAD

**Issue by mattlanham** [vfr/Reader#71]
Is there anyway of having a layout that supports 2 page spreads when the iPad is in landscape mode?

**Comment by boardmain** [comment]
i hope this will be integrated soon

**Comment by devios1337** [comment]
This would be great, but please iPhone landscape too not just iPad!

**Comment by gouravfxbytes** [comment]
Can any one suggest any alternative for 2 page in landscape, i had tried but with creating two different object that cause memory issue.

**Comment by AlbertoLourenco** [comment]
@etabard , you saved my life! But, please add this feature on the actual version. :D

Thanks!

**Comment by etabard** [comment]
@AlbertoLourenco Thanks :-)

My PR has been rejected. They are maybe working on a "clean" solution...

**Comment by pahnev** [comment]
Looking at all the closed PR's, without implementation, I doubt that they are.

**Comment by AlbertoLourenco** [comment]
@etabard  I created a version with your solutions and the actual library version. If you want my version, please send me an email.

alberto.lourenco8@gmail.com

**Comment by tibo6** [comment]
I look forward to this feature :)

**Comment by dungiBear** [comment]
:) Are there any Updates to the 2 Page Support?
