### ISSUE TITLE
Could URL's be opened in a subview, instead of Safari?

### ISSUE THREAD

**Issue by pahnev** [vfr/Reader#77]
Hi, just thought that it would be nice if clicking url in the pdf would keep the user in the app, instead of opening Safari. Especially since iOS doesn't have back button like Android and jumping between apps is sometimes pain in the ass.

I'm trying to do this myself and I have found the place where we get the clicked URL, or at least I think, but it is a bit too complicated for me to understand what is handling the opening after that.
Could someone point me to right direction?

**Comment by dfmuir** [comment]
You can use KINWebBrowser to present a KINWebBrowserViewController and pass in the URL.

https://github.com/dfmuir/KINWebBrowser
