### ISSUE TITLE
App Rejected

### ISSUE THREAD

**Issue by wapfa** [vfr/Reader#84]
Hi,

My App was rejected twice because of this reason given by Apple reviewer:
______________________________

Reasons:
2.23: Apps must follow the iOS Data Storage Guidelines or they will be rejected

At the first time, I thought it happened because I left marked iCloud option in the provisioning profile.

But no, they keep stating the following:

We found that your app does not follow the iOS Data Storage Guidelines, which is required per the App Store Review Guidelines.

In particular, we found that on launch and/or content download, your app stores 9.03MB. To check how much data your app is storing:

- Install and launch your app
- Go to Settings > iCloud > Storage & Backup > Manage Storage 
- If necessary, tap "Show all apps" 
- Check your app's storage

The iOS Data Storage Guidelines indicate that only content that the user creates using your app, e.g., documents, new files, edits, etc., should be backed up by iCloud. 

Temporary files used by your app should only be stored in the /tmp directory; please remember to delete the files stored in this location when the user exits the app.

Data that can be recreated but must persist for proper functioning of your app - or because customers expect it to be available for offline use - should be marked with the "do not back up" attribute. For NSURL objects, add the NSURLIsExcludedFromBackupKey attribute to prevent the corresponding file from being backed up. For CFURLRef objects, use the corresponding kCFURLIsExcludedFromBackupKey attribute. 

For more information, please see Technical Q&A 1719: How do I prevent files from being backed up to iCloud and iTunes?.

It is necessary to revise your app to meet the requirements of the iOS Data Storage Guidelines. 
If you have difficulty reproducing a reported issue, please try testing the workflow described in Technical Q&A QA1764: How to reproduce bugs reported against App Store submissions.

If you have code-level questions after utilizing the above resource, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:

- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log
_________________________

I can't even check iCloud storage of the App, since it's not being stored in the iCloud !!!

Any Idea how to fix it?

By the way, I'm not using Newsstand and I'm simply replacing the PDF-demo.

I've being using VFR for two years and it was the first time Apple rejects it.

Thanks in advance, Julius and community

**Comment by pahnev** [comment]
Just adding this stackoverflow question here for easier access

http://stackoverflow.com/questions/19964831/ios-flag-entire-document-directory-as-do-not-backup
