### ISSUE TITLE
The UISrollView not works after move to the next 2 or 3 pages and go back again

### ISSUE THREAD

**Issue by javiergonzper** [vfr/Reader#88]
On an iPhone 5 with iOS 8.1.2 after go forward some pages and go back to one the UIScrollView looks like frozen.

Steps:
-Open a PDF.
-Go forward 3 pages
-Go back the the previous page

In this point you can not go to the next or the previous one.

Here you have a video about the bug:
https://s3.owncloud.com/owncloud/index.php/s/gQm3uHcGV4SVnTO

**Comment by Shumais** [comment]
In ReaderContentView.m, 
Go to the "Initialize" method on line#82
Remove the 4th IF condition : if ([@"8.1.1" compare:iosVersion options:NSNumericSearch] == NSOrderedDescending) // Below 8.1.1
But keep the statement inside it.

So you will have 3 IF conditions and the third one will look like this:

if ([@"8.0" compare:iosVersion options:NSNumericSearch] != NSOrderedDescending) // 8.0 and up {
                g_BugFixWidthInset = 2.0f * [[UIScreen mainScreen] scale]; // Reduce width of content view
}

I have also created a pull request (but I dont know how to add a link to it here, if it is possible in the first place).

**Comment by javiergonzper** [comment]
Hi @Shumais,
It works! Thanks a lot for your help :+1: 

I thinkg that just with the link the pull request appear.
https://github.com/vfr/Reader/pull/90

**Comment by vfr** [comment]
Can some try 2.8.6 with iOS 8.2?

Not able to reproduce this under iOS 8.2 on an iPod touch 5th gen or iPhone 6 Plus.
