### ISSUE TITLE
Swiping getting stuck

### ISSUE THREAD

**Issue by helmesjo** [vfr/Reader#89]
(same issue as posted in viewer)

If you swipe casually through a pdf (swiping quick seems to be working) it will eventually get stuck, and when you try to swipe the page just flickers but stays at the same page. If you pinch-zoom out and release it will start working again (just to get stuck soon enough).

Currently running on an iPhone 5, iOS 8.1.3.

This happens in the example.

**Comment by pahnev** [comment]
Same as #88 perhaps?

**Comment by helmesjo** [comment]
I didn't know that (didn't mean #88), but I posted this same issue for the "Viewer". But since it's most likely related to the Reader I posted it here too. If anything, I'll remove it from the Viewer! :)
