### ISSUE TITLE
The pdf remarks are not shown on the VFR Lib

### ISSUE THREAD

**Issue by javiergonzper** [vfr/Reader#92]
For example this file with the title remarked on yellow is shown on the VFR Lib without the yellow remarked.
https://s3.owncloud.com/owncloud/index.php/s/E47qtgtsWPQGPrU

![captura de pantalla 2015-03-19 a las 13 22 30](https://cloud.githubusercontent.com/assets/1815050/6730257/11d0ea48-ce3b-11e4-96a1-9c0a32244f71.png)

Looks like the VFR Lib can not load the different layers that have the PDF

**Comment by vfr** [comment]
The code uses iOS' built-in PDF rendering capabilities. That might be an annotation of some kind. If so, then you need to parse the PDF page looking for annotations and render them yourself.
