### ISSUE TITLE
Ability to read remote pdf's

### ISSUE THREAD

**Issue by Reedyuk** [vfr/Reader#95]
Hi,
Say i have a pdf hosted somewhere, then it would be nice if i could just pass the url and the reader can handle it(i guess by downloading it and then opening it).

**Comment by ndastur** [comment]
Maybe, but this is a PDF reader. I would suggest that file downloading is handled by the appropriate different library. A good download library will handle network errors do retries etc etc so the implementation would be non trivial.

**Comment by Reedyuk** [comment]
I disagree, i think that it should be an option so that if we pass in a remote url then it should attempt to retrieve the file, otherwise a local file it would just load.
That way, we still have the ability to download and handle the file if we want to.

**Comment by spnkr** [comment]
Reedyuk, try https://github.com/AFNetworking/AFNetworking for downloading via HTTP

**Comment by SPopenko** [comment]
+1 for this issue, this is something cool to have and looks like a blocker for me.
