### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'CGPDFDocumentRef == NULL'

### ISSUE THREAD

**Issue by function2000** [vfr/Reader#98]
My code as below:
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
  {
  
  pdf  *pdfEntry = [[self fetchedResultsController] objectAtIndexPath:indexPath];
  
  NSString *phrase = nil; // Document password (for unlocking most encrypted PDF files)
  
  //NSArray *pdfs = [[NSBundle mainBundle] pathsForResourcesOfType:@"pdf" inDirectory:nil];
  
  //NSString *filePath = [pdfs firstObject]; assert(filePath != nil); // Path to first PDF file
  
  NSString *filePath = pdfEntry.pdf_local_path;
  
  ReaderDocument *document = [ReaderDocument withDocumentFilePath:filePath password:phrase];
  //ReaderDocument *document = [[ReaderDocument alloc] initWithFilePath:filePath password:phrase];
  
  if (document != nil) // Must have a valid ReaderDocument object in order to proceed with things
  {
      ReaderViewController *readerViewController = [[ReaderViewController alloc] initWithReaderDocument:document];
  
  ```
  readerViewController.delegate = self; // Set the ReaderViewController delegate to self
  ```
# if (DEMO_VIEW_CONTROLLER_PUSH == TRUE)

```
    [self.navigationController pushViewController:readerViewController animated:YES];
```
# else // present in a modal view controller

```
    readerViewController.modalTransitionStyle = UIModalTransitionStyleCrossDissolve;
    readerViewController.modalPresentationStyle = UIModalPresentationFullScreen;

    [self presentViewController:readerViewController animated:YES completion:NULL];
```
# endif // DEMO_VIEW_CONTROLLER_PUSH

```
}
else // Log an error so that we know that something went wrong
{
    NSLog(@"%s [ReaderDocument withDocumentFilePath:'%@' password:'%@'] failed.", __FUNCTION__, filePath, phrase);
}
```

}

But when running, error occurs:

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'CGPDFDocumentRef == NULL'
**\* First throw call stack:

Please help. Thanks!

**Comment by function2000** [comment]
after delete the app, and run it again, works now.

**Comment by function2000** [comment]
sorry, come back again. this is not solved. After run about 10 times, this error occurs again. Please help to solve it.

**Comment by KKKKaras** [comment]
how to solve it ?  I need  help  :(

**Comment by altaveron** [comment]
The issue happens always in iOS 8 Beta 5. The issue is CRITICAL.

**Comment by altaveron** [comment]
http://stackoverflow.com/questions/31934333/ios-9-beta-5-cgpdfdocumentcreatewithurl-is-return-nil-only-password-protected

**Comment by wacumov** [comment]
The issue sometimes happens, sometimes doesn't. It is weird.
